### ISSUE TITLE
Great feature, couple thoughts.

### ISSUE THREAD

**Issue by bsavery** [CGCookie/blender-addon-updater#15]
So we're integrating this to the RenderMan for Blender addon.  Really think this is the missing piece for addons in Blender.  Very clear code and instruction thanks!

Really my only question is the default of 7 days for the update.  I'd claim that 1 day is fine!  That's what we set.

**Comment by johnroper100** [comment]
You can set it to be 7 days if you would like to.

**Comment by carter2422** [comment]
Thanks @bsavery and nice going getting it integrated so quickly. 

The frequency of checks for updates is something I think should be left mostly to the individual developers, but you're right that 7 days by default may be too long. 

Being as this isn't an issue per se, I'll go ahead and close this but thanks for the interest and let us know if you run into any issues!

**Comment by bsavery** [comment]
Agreed.  Oh and the other thing I thought about was if a user wanted to set the automatic update to grab the latest of some branch other than master that isn't currently possible.  Just something to think about doing.

**Comment by TheDuckCow** [comment]
Yup, that's a good point @bsavery as it's typically the developers who would want branch access anyways. Depending on how crazy we want to get, could even expose specific commit access.

Re default value, yeah honestly even the already built-in methodology of once per blender instance as the absolute highest frequency is stable and wouldn't cause any user harm. I think once a day actually would be appropriate since it doesn't hang blender at all and, somewhat defeats the purpose of the updater if it takes up to 7 days to notify you of something updating. Should be up to the developer (and thereafter to the user themselves on what defaults they want to save preferences to), but I think changing to 1 day would be a fair approach.
