### ISSUE TITLE
Error message with disable/enable

### ISSUE THREAD

**Issue by stilobique** [CGCookie/blender-addon-updater#18]
Hi,
my addon make an error when i'm re-enable it.

To be more clear, watch this Gif :) .
![bug_auto-updater](https://cloud.githubusercontent.com/assets/3066684/22670814/4cb388d6-eccb-11e6-8c69-7d16b2e420e2.gif)

And the message error.
![msg_error](https://cloud.githubusercontent.com/assets/3066684/22670850/775a96ba-eccb-11e6-9c90-50e0d79f0765.jpg)

**Comment by TheDuckCow** [comment]
Thanks for reporting the issue. I'll look into why that is occurring, but can you confirm that excluding the importer code (or before you added it) did not create re-enabling errors? Can you confirm that you "renamed" the addon by changing the string atop the addon_updater_ops.py file to something other than the default?

**Comment by TheDuckCow** [comment]
Hello @stilobique, the problem here was how registration is used. If you look in the addon updater ops file, you should see the following comments on line 781-783 from the file in your substance repository:

```
    # The register line items for all operators/panels
    # If using bpy.utils.register_module(__name__) to register elsewhere
    # in the addon, delete these lines (also from unregister)
```

Since you are using this method of addon-wide registration, the lines of code following that which explicitly register the operators are duplicate registers. So you may simply delete or uncomment those lines like so:

![remove regstration calls](https://cloud.githubusercontent.com/assets/2958461/22737625/dbc0c352-edd1-11e6-85c6-41eeeaf121fa.png)

Please let me know if this works out.

**Comment by stilobique** [comment]
Hi,
sorry to answer only now, i can check this week-end only. Thanks for your support !

**Comment by stilobique** [comment]
Hi,
I'm currently check my error, and yes it's that. But i don't unterstand why this error. I don't use the register_module methode. But i'm resolve my issue, i'm create a new function to check the version ; and it's functional !

Thanks for your support again, and great's addon. 

Edit : I don't no if you wan't see my issues or if it's necessary to share it here. The code can be found in my SubstanceBridge addon (not in master branch, in the dev branch).

**Comment by TheDuckCow** [comment]
Okay great, and yeah I think it's because it's used at the addon init module level and so it propagated into submosules too. Glad it is working! Closing now.
