### ISSUE TITLE
Updating for multiple OSs

### ISSUE THREAD

**Issue by johnroper100** [CGCookie/blender-addon-updater#24]
Now that we are moving CrowdMaster over to python, we need to make separate released for macOS, Windows, and Linux. Currently, the addon updater does not know the difference between OSes. Would it be possible to have a system that reads in three different release repositories and downloads the correct version for the user's OS?

**Comment by TheDuckCow** [comment]
Changing title from "_Updating for multiple OSs_" to "Support binary downloads"

This can be supported if we can direct being able to download and use attached zip files to the release, as opposed to the raw release code itself. Some logic would have to be applied and inserted by the user if needing to decide between which 3 or however many available builds, but if there are ever situations with just a single build to attach, then it could be made to try to automatically just use the one file available.

John in your case as discussed for CrowdMaster, it may be best to have some kind of hard coded or token value within each of the three builds to universally confirm the type of build downloaded. WHile we can have python guess, it would be frustrating if it wasn't perfect and the python thought it was e.g. linux when in fact the user had downloaded the mac version.

**Comment by TheDuckCow** [comment]
This has effectively been enabled through the inclusion of the new `select_link_function` which allows for targeting specific asset downloads over using the default included source code with a tag/release. Requires setting `updater.use_releases = True` and having a valid, consistent naming structure of attachments to these releases. 

Closing for now, any further issues with how that functions can be added as new issue

**Comment by schroef** [comment]
GLad my release function could help here. NOt sure what happens though when 3 OS system zips are there per release, did you test this?

**Comment by TheDuckCow** [comment]
I wrote some (untested) sample code to look at that, since the assets have names associated with them, you could check against a naming convention of the supplied attachments and write some code to compare against the running host operating system (that part I have used before, so I know it works that way). If I get some time later, I may do a more proper test and tweak to ensure it works as-is in case someone ends up wanting to use it that way. 

https://github.com/CGCookie/blender-addon-updater/commit/21bbcdd433227f8d122362fececd47b281761708#diff-59a84a958bbe9b22468107144e433486R1022

Note that it's structured a bit differently now to how you had it, I've separated out the concept of "use_releases" from using release-attachments as source for the code. While you need to use releases in order to use attachments/"assets", it is possible to use releases but not want to assets (e.g. to get tag names, release logs, or to filter out non-annotated tags, etc). And so, I set it up such that this function `select_link_function` is called when determining what download link to use in the given API's; majority of cases it remains the same, ie `link = tag["zipball_url"]` as it was for all before. 

Final note for reference is, only GitHub has the concept where a release is materially different from a tag, in GitLab and Bitbucket they are the same thing and there is no difference, also you can't attach files/builds the same way so pretty much the change only applies to GitHub-hosted addons. Anyways, all that was just an FYI in case you were curious!

**Comment by schroef** [comment]
Oke is that easy to search within text, ive use such a for ... in if ... just once in different project. Dont completely understand it. 

Thats indeed an easy way to do it by adding OS to the nameing

**Comment by TheDuckCow** [comment]
It’s a pretty useful convention, I use it a lot (and it often can be a performance boost, is it compiles to C-loop processing in many cases; more relevant to image processing than here though). A nice breakdown of how it works and the equivalent is here (http://www.pythonforbeginners.com/basics/list-comprehensions-in-python). 

In the example I share, it’s a little bit of a lazy way to program it I suppose, as the [0] assumes at least one match exists and there’s no real error checking. That I might improve as I do the more real test example.

**Comment by schroef** [comment]
I need to learn more about coding and python :) I just started by adding small items in render addon for blender. Ive been doing this for about 1-2 years now. While doing it mainly by reading and looking at functions, i learned a bit. I did some AS scripting in my old flash days, never was a guru or anything. Though this did help a bit understanding python more.

I dont have much knowledge op Python, i try and try and try until errors are gone :) When i dont it fixed, ill google my error output. 

I understand basic for and while loop, but this C-loop processing is a bit new for me. It seems to be like for if loop but it runs much faster i guess.
