### ISSUE TITLE
GPL license.  

### ISSUE THREAD

**Issue by bsavery** [CGCookie/blender-addon-updater#25]
So, kinda a high priority issue here.  I just realized that the addon updater code is done under the GPL license.  This makes it impossible to use under MIT license addons.  (Without the addons being switched to GPL).  Many people hate this, and it will become unviable very quickly.  We are probably going to have to remove this from RenderMan for Blender actually sadly.

Have you thought about dual licensing MIT and GPL?  Pretty common, jquery does it for instance.

**Comment by carter2422** [comment]
Hey @bsavery, myself and @TheDuckCow are going to review the license and what options there may be. Thanks for the heads up; we'll get back to you.

**Comment by bsavery** [comment]
Appreciate it.  Thanks.

**Comment by jdent02** [comment]
Hey guys.  Did anything ever come of this?

**Comment by vxlcoder** [comment]
I've pinged @TheDuckCow about this.  Sorry that this issue is still ongoing!

**Comment by jdent02** [comment]
That's fine.  Was possibly looking at incorporating this into the Appleseed exporter and it's MIT too so the same issue would apply.

Thanks for the help!

**Comment by TheDuckCow** [comment]
Hey there, sorry the response was not placed here before. As per (https://www.blender.org/support/faq/), all blender addons/scripts (or at least, anything that imports and uses the bpy module) must be by definition licensed as GPL. Sometimes this is not realized by developers, but for this reason we cannot sublicense the blender updater as it is to anything other than GPL. My only side comment is that the addon_updater.py file is darn near without any bpy uses (it does the more direct, raw internet requests and processing which is independent to blender) so it would be conceivable to release a version of this separately and also under MIT for non-blender use cases. 

Happy to discuss further on the matter. I know many companies find issues with the GPL license from risk and commercial product license reasons, but it's generally reasonable to work through them and find a way to make GPL blender addons talk in a legitimate way to non GPL/a commercial  engines/programs.

**Comment by TheDuckCow** [comment]
Closing the issue for now as licensing constraints will not be changing, thanks for engaging in the dialogue about it here and offline.

**Comment by schroef** [comment]
What is the deal between these 2 licenses MIT and GPL, they both seem to state the same thing almost. What i do find sort of strange is that say to operators are written in the same way, how can you ever tell if one has been made under GPL and the other MIT. I mean they both use Python, python is a language and its 100% possible that 2 persons code the same operator. I tried looking into this and even found that in Germany 2 cases where started with GPL being the subject in manner.

**Comment by TheDuckCow** [comment]
@schroef licensing and the code itself are completely different, you can't tell what code is one license or another just by looking at it - rather, a license is a set of rules for what *you are allowed to do* with the code.

You are correct, MIT and GPL are similar in that they are both open source (ie anyone can copy and contribute), but they do differ in a few key ways - GPL is "stricter" about being more open ([read more here](https://choosealicense.com/)).

As it pertains to blender python addons, **all addons are GPL**. It is not up to the developer to decide, because GPL is copy-left and the BPY module is itself already GPL. Any blender addon claiming to be something other than GPL (e.g. MIT) is in fact wrong. This is essentially decided by the nature of how the Blender Foundation has released blender itself and its customized python libraries. 

Generally a developer is free to license and use whatever terms they want (or even invent their own), though the code developed can be subject to licensing constraints of any libraries the program/code uses. In this case, blender libraries like bpy (which are used in all blender addons) come with the GPL requirement for the addon that uses it. 

In the scenario where it's possible to code the same thing by two different people: yeah that's a bit fuzzier. But that gets less likely for larger more complex things, which is where these sorts of licenses come into play - ie when someone wants to *build* on top of the code already done by someone sometime before, instead of starting from scratch. 

Happy to point to further resources if you're curious. Also I'm 100% not a lawyer so don't take any of this to a court of law 😄

**Comment by schroef** [comment]
Okay so if the BPY library it self is already GPL, how can people than make paid addons using bpy, isnt so then that these needs to be GPL as well according to GPL rules?

**Comment by bsavery** [comment]
They can still make paid addons, GPL doesn't disallow that.  It's just they have to "make the source available".   Quotes around that are intentional as that is exactly what it says.  I have read differing accounts as to who or how that source must be available.  For instance, could you only make the source available in hard copy printed out form?  

This could quickly devolve into a debate about GPL and commercial viability for addons to Blender.  But my personal feeling is that the desire to encourage commercial addons and real studios using blender might make it in everyones best interests to not be GPL nazis here in the Blender community.

**Comment by jdent02** [comment]
You underestimate the volume of the ‘everything Blender should be FREE’ crowd 😁

**Comment by TheDuckCow** [comment]
@bsavery hit the nail on the head, GPL specifies that you must make the source code available 'within reason', which leaves a lot to be interpreted (e.g. using absurdly high prices as an indirect way to effectively make the source code closed while still being "compliant" with license restrictions, though I'd imagine it would likely be deemed at odds with the intent of GPL if it ever in court).

There are plenty of points to be made to, for, against, and aside of this GPL and general licensing discussion for blender and the strictness/interpretation of defending it - perhaps better suited for forums.

**Comment by schroef** [comment]
I was just curious, it sure is a difficult and awkward subject. Thanks for all the info!
