### ISSUE TITLE
update shows wrong version

### ISSUE THREAD

**Issue by kromar** [CGCookie/blender-addon-updater#52]
i added your updater to an addon and noticed that it shows the update to the already installed version. 
i was wondering if i possibly did some mistake configuring the update conditions or if this is a issue with the updater.

![image](https://user-images.githubusercontent.com/1472884/57966264-beae9300-794f-11e9-8358-afa2c64b1ce5.png)

i also had a user report a version downgrade as update
![image](https://user-images.githubusercontent.com/1472884/57966313-65932f00-7950-11e9-9849-723670bd0e6b.png)

**Comment by TheDuckCow** [comment]
Hi, not sure if you since realized but the reason is that it checks the whole version tuple. So, in python, (28, 3, 0, 2) is viewed as larger than (3, 0, 2) and thus it thinks its an update. Tuples use the leading digits as the most significant.

If you really need to have two different releases for 2.8 and 2.7 while still maintaining the same version numbers, I'd recommend you update the tag function to ignore e.g. releases which have the first release digit as 28 if it's blender 2.7, and if its 2.7 then only include if it doesn't have this. Then in blender, you should match the same version number.. ie 28,3,0,2 instead of 3,0,2 (or, else modify the source code some to dynamically strip the leading tuple integer if it equals 28). 

Hopefully this helps.

**Comment by kromar** [comment]
hi, yes i realized how the version gets read, and adjusted the tags and branch filtering.

we have however a different issue now since we have a tag scheme with dots (v3.0.2) that however creates a issue with the releases on github which have the version in the filename that is downloaded and blender when installing this will create a folder GoB-v3.0.2 and cant read it because it thinks the dots define a file extension or so.
So the question now is can we use underlines in the tags (v3_0_2) and the updater will be able to compare this to the blender version tuple?

**Comment by schroef** [comment]
I believe you can also use tags instead of file versioning. Its been a while, but i believe i added something like this or it was the releases part. Otherwise, check if you can change to dotted versioning :)
