### ISSUE TITLE
(2.8) Enabling old addon messages

### ISSUE THREAD

**Issue by marcopavanello** [CGCookie/blender-addon-updater#53]
![Screenshot](https://user-images.githubusercontent.com/8861988/58094798-c67d6a00-7bd1-11e9-8810-da4430de4b24.jpg)
Hello, i'm having these messages in the terminal when enabling an old addon that automatically finds a newer version.
Here is my addon: https://github.com/macio97/Real-Camera

**Comment by schroef** [comment]
My guess is because you use blender from the standard unzipped folder. It has a lot of dashes and underscores. Can you try renaming the folder simply blender or blender280. No dashes or underscores

**Comment by marcopavanello** [comment]
Nope, i have no dashes or underscores in the addon folder. Don't watch the messages before the red row, they are messages i needed, just look at the ones after the red row. By the way, updating to the newer version works, it just prints these messages.

**Comment by schroef** [comment]
Yes you do have underscores and dots in the name. You unzipped the Blender 2.80 and didnt get rid of the hashcodes

![Screen Shot 2019-05-23 at 13 21 50](https://user-images.githubusercontent.com/6923008/58273054-da55d700-7d5d-11e9-813e-19d360843e22.png)

But im not sure i follow you, i think your not English speaking and translate messed up the essence.
What is the exact issue now than?

You need to add a regular dash to your Addon folder by the way. Regular dashes are fine i believe, but underscores and dots in names can be a problem. These are reserved characters.
![Screen Shot 2019-05-23 at 13 23 54](https://user-images.githubusercontent.com/6923008/58273459-c363b480-7d5e-11e9-9a9c-00e662df205e.png)

Check if adding adash in that folder name perhaps solves the issue. 

Otherwise, its the post script causing it. Some items in the API are changed with pre and post handlers.

The addon update itself work fine without those errors you show, so this is related to your system.

**Comment by TheDuckCow** [comment]
Hey @macio97, sorry for the delay - sent a reply by email but didn't realize it got stuck in my outbox. Thanks @schroef for offering some thoughts as well.

You've uncovered an actual bug in the code, thanks for reporting! Blender 2.8 has removed the scene update handler in favor of other options like dependency graph refreshes or explicit timers. I will need to update the code and push a release to account for this. 

Note, for anyone else that comes across this, the only impact from my testing and looking at my own code is that the actual popup "hey new version here, press ok to install!" will not show, but everything else should appear (such as the popup confirming that an install completed, and the the appearance in a panel where updater info is placed).

**Comment by marcopavanello** [comment]
Thanks to you man :) i'm using your scripts since years and they really help! Continue like that!

**Comment by TheDuckCow** [comment]
Officially fixed now in the v1.0.8 release (which includes using a different handler now available for this purpose).
