### ISSUE TITLE
Can't install Addon 

### ISSUE THREAD

**Issue by LorenzWieseke** [CGCookie/blender-addon-updater#61]
Im developing in vs code and connecting it to blender via Jacques Luckes extention.
Everything works nicely and no errors but when I push to git, download the release and try to install it from scratch I get this error if I try to enable the addon :

![image](https://user-images.githubusercontent.com/29607121/83742826-2a969300-a65a-11ea-89bb-227ed0c34678.png)

It seems that a -0 is added somewhere to the module name but I don't get where .

The repo is here : https://github.com/LorenzWieseke/GLBTextureTools/releases

Thanks in advance !

**Comment by LorenzWieseke** [comment]
Ok, so now I figured out that it has something to do with the tag number.
When I use v1.0.5 like in your addon it gives me the same error but only it cant find GLBTextureTools-1 this time 

![image](https://user-images.githubusercontent.com/29607121/83807592-a244dc00-a6b3-11ea-8c67-22eed964bd09.png)

But when I change the release tag on github to just v5 it works cause there are no extra dots in the file name 

![image](https://user-images.githubusercontent.com/29607121/83807719-d28c7a80-a6b3-11ea-91c9-07780edb90ba.png)

I still don't get why it's not working with the 0.0.x format and why it works in all your addons.

**Comment by LorenzWieseke** [comment]
![Naming_Error2](https://user-images.githubusercontent.com/29607121/83869194-7e71ac80-a72c-11ea-99aa-5a91a9a49ac6.gif)


Is there any way to fix this because I need the veriosn number to be in the x.x.x format ?

Does it have something to do with my __init__.py ?

**Comment by LorenzWieseke** [comment]
Ok, found this :
https://developer.blender.org/T50042

It seems to be a convention not to use "." in file names but why does it work on so many other addons (including the auto updater) and not in mine ?

For now it seems I need to go with "_" instead of "."

**Comment by TheDuckCow** [comment]
Hi there, so sorry for the delayed response. 

Took me a second but I realize that indeed, this is true for all addons - but a slight nuance:
- The zip file itself can have any name, including periods
- But, the actual FOLDER contained inside the zip file must not contain any periods, as this folder name is used as the module identifier for the addon (this is also how you can have multiple versions of the same addon installed at once but named the same, if they have different folder names in the blender scripts/addons folder).

Example addon of my own (showing the full link for transparency)
https://github.com/TheDuckCow/MCprep/releases/download/3.2.3.1/MCprep_addon_v3.2.3.1.zip

That is a zip file that I have attached to the release (is not the auto generated code package) where the file itself has periods, but if you were to download and extract, you'd see the root object is actually a folder "MCprep_addon". For the end user, the manual work around is to unzip the versioned zip file, change the root folder name, and rezip. Or, you could use the same approach as MCprep here, where you attach zip files to releases where you have already done the fix for your users. It's a manual step, but makes it more seamless.

Your approach of using _'s though is totally fair as well, maybe just not as nice to read but gets the job done.

**Comment by LorenzWieseke** [comment]
First of all thanks for the reply, I searched a lot and couldn't find any solution. 

I tried your solution to manually zip the whole project and add it as binary to the release. I also tried to automate that process with the help of github actions but I didn't get it to run properly.

Now the initial activation it self works but as soon as I update using the auto updater I get an error on the next restart.

![image](https://user-images.githubusercontent.com/29607121/84015705-8a53ad80-a97c-11ea-88d0-513e5fa4dad9.png)

I know this error is releated to how I import the addon in my panel but I don't get why it works the first time.

The auto updater addon itself also has the x.x.x format in the folder that is zipped and here it works too, but why ?

https://github.com/CGCookie/blender-addon-updater/releases

![image](https://user-images.githubusercontent.com/29607121/83952358-b1a16200-a838-11ea-8ff7-8afc9223343d.png)

**Comment by LorenzWieseke** [comment]
Now I removed the panel functionality to avoid the import error but the updated doesn't work. If I install an older version and update to 0.0.7 or master its still on 0.0.6

![No_Update](https://user-images.githubusercontent.com/29607121/84018322-30ed7d80-a980-11ea-83e7-443133483996.gif)

**Comment by TheDuckCow** [comment]
Hi - I just downloaded your latest release, and while the tag of the release indeed says 0,0,7 - the actual version number in the blend `__init__.py` file still says 0,0,6. Just be extra careful that the code released has the exact matching set number in bl_info as in the release name itself. Let me know if that doesn't seem to fully clear this up. Sorry I can't comment further on the panel registration issue, I'd have to look more closely at the addon code and module importing done there.

**Comment by TheDuckCow** [comment]
Just a quick follow up here - did the above resolve your issue? Let me know, and I'll close the issue.

**Comment by LorenzWieseke** [comment]
Sorry I skipped using the auto updater cause it was difficult to test with all the pushing to git and rebasing to cleanup the mess, maybe I'll try it again now that I solved the naming issue.

I added a github workflow that zips the files and attaches a zip to the release, just in case anyone needs it :
[auto_deploy.zip](https://github.com/CGCookie/blender-addon-updater/files/5067797/auto_deploy.zip)

**Comment by TheDuckCow** [comment]
Resolving this now because 1) I think the issue was resolved? and 2) It's quite old and I think a specific implementation. Please reply though if the struggle persists, apologies for my much delayed response!
