### ISSUE TITLE
GitHub API shouldn't be trusted for tags order

### ISSUE THREAD

**Issue by Dragorn421** [CGCookie/blender-addon-updater#65]
# Context

I'm using this updater for an addon (irrelevant I think but here it is https://github.com/CrookedPoe/io_export_objex )

Configuration part of addon_updater_ops.py : https://github.com/CrookedPoe/io_export_objex/blob/master/io_export_objex2/addon_updater_ops.py#L1354

# Issue

At the moment there are two tags `2.79_only` and `2.0.0`, created in that order. The updater thinks `2.79_only` is more recent though.

`2.0.0` is indeed more recent as per the releases page https://github.com/CrookedPoe/io_export_objex/releases (screenshot below)

![screenshot of releases on the 11th of august](https://421.es/doyu/1ll5za)

# What the GitHub API says

The API indeed puts `2.79_only` first

https://api.github.com/repos/CrookedPoe/io_export_objex/tags

```json
[
  {
    "name": "2.79_only",
    "zipball_url": "https://api.github.com/repos/CrookedPoe/io_export_objex/zipball/2.79_only",
    "tarball_url": "https://api.github.com/repos/CrookedPoe/io_export_objex/tarball/2.79_only",
    "commit": {
      "sha": "1af434a1c02f8c36f8930f64b192fba59fa68d93",
      "url": "https://api.github.com/repos/CrookedPoe/io_export_objex/commits/1af434a1c02f8c36f8930f64b192fba59fa68d93"
    },
    "node_id": "MDM6UmVmMTQ2MjMyOTAyOnJlZnMvdGFncy8yLjc5X29ubHk="
  },
  {
    "name": "2.0.0",
    "zipball_url": "https://api.github.com/repos/CrookedPoe/io_export_objex/zipball/2.0.0",
    "tarball_url": "https://api.github.com/repos/CrookedPoe/io_export_objex/tarball/2.0.0",
    "commit": {
      "sha": "7c5cf5879f92da930fec7f1b9df47ed346935e12",
      "url": "https://api.github.com/repos/CrookedPoe/io_export_objex/commits/7c5cf5879f92da930fec7f1b9df47ed346935e12"
    },
    "node_id": "MDM6UmVmMTQ2MjMyOTAyOnJlZnMvdGFncy8yLjAuMA=="
  }
]
```

As per the blender/blender tags more recent should indeed be first though: https://api.github.com/repos/blender/blender/tags

# Cause

I pushed (`git push --tags`) the two tags in the same `git push` so that may be why this happens

# Fix

I think the addon should somehow sort tags correctly, based on latest commit or somehow getting the tag time like on the releases page, since the GitHub API doesn't seem to sort tags as is thought

It may be best as an option since I guess it would take more requests over the internet

I am not familiar with the GitHub api, not sure what exactly can be done

In the mean time, is there an option to set in addon_updater_ops.py that could make 2.0.0 the chosen tag instead of 2.79_only?

**Comment by TheDuckCow** [comment]
Hi there,

At the moment, the updater is design to parse the tag names only and derive whether or not there are updates based the largest found parsed tuple, not based on the time of the release, since releases could be non chronological. In your case, I believe it is treating the tuples 2.0.0 as (2, 0, 0), and 2.79_only as (2, 79), which in python, tuple compare left to right first and so the 2.79 release would be marked as more recent.

Your solution is to create an override in the skip_tag function, see [this line here](https://github.com/CGCookie/blender-addon-updater/blob/master/addon_updater_ops.py#L1241) - if that tag is going to remain, and you never need anyone to "update" to it, then I'd just hard code the name in the updater so that it ignores (skips) that tag when parsing. Let me know if that solves your issue.

**Comment by Dragorn421** [comment]
That makes sense.

Filtering out the `2.79_only` tag did the trick, thanks! ( https://github.com/CrookedPoe/io_export_objex/commit/55ec706f1be85a823c16305cec0ef9ae1c71017d )
```py
	if tag['name'] in ('2.79_only',):
		return True
```

Thanks for the quick answer! Have a nice day.
