### ISSUE TITLE
Ignore, i'll look for a delete button

### ISSUE THREAD

**Issue by studiomonkriss** [CGCookie/blender-addon-updater#69]
How do i delete... I had a problem but i think i may have solved it

**Comment by TheDuckCow** [comment]
No worries! Closing is the right action. And just for record's sake, my guess is that you created a "tag", but the repo was set to read "releases" (which are annotated tags), is that right? If not, sharing your experience of what you got stuck on and what you did to fix it might help others too. Cheers!

**Comment by studiomonkriss** [comment]
Hey thanks for your response!

I have investigated it some more with the idea that I had, and actually the code we were using was about 14 months old, so I copied the script from your latest update and put that in place of the old files -
old addon_updater.py
addon_updater_ops.py

It now reads the versions correctly and I can select them! Yipee... however now I get another error. I didn't want to bother people here who seriously know what they are doing with my little questions so I was going to keep digging and seeing what I can find. Also i'm learning a TON by all this troubleshooting.

If you have any ideas with this error message that can point me in the right direction then that would be fab.

[https://imgur.com/a/KJAINag](url) - Hmm i think I did the URL wrong https://imgur.com/a/KJAINag

**Comment by studiomonkriss** [comment]
This error is when i click Update as it says "new version available"

**Comment by TheDuckCow** [comment]
Don't worry about commenting, it's what this part of the repo is for! Though, troubleshooting is a great way to learn as you say, so that's fair too :)

The first error appears that it cannot find the source folder, so might be worth double checking manually if that path mentioned actually exists or not. The second error is coming from what may have been a partial mistake of more recent commits. I see this print_traces might not have bene added correctly, so thanks for sharing this. I need to check locally, but I believe that the function `def print_trace():` needs to be redefined as `def print_trace(self):` (with self, since it is a method defined within a class). I just pushed an update regarding this point. This will help you debug what is actually happening in the first traceback itself.

**Comment by studiomonkriss** [comment]
Ah okay I see, I just checked and it looks like on the error message it is missing one last folder "update_staging"
https://imgur.com/a/QkspqQK

I'll see if this is something I can find out why...

And okay cool i'll have a look into that second part! I'll maybe try the (self) option and see what happens 👍

**Comment by studiomonkriss** [comment]
Success!!

I changed to def print_trace(self) - now it appears to work completely. Ive done a few version bumps and all appear to allow me to install the latest version. Amazing! thank you for your help

**Comment by TheDuckCow** [comment]
Great, glad to hear it! If indeed this is working for you, I’ll likely move to create an official release based on the current code as well.

**Comment by studiomonkriss** [comment]
Yep I just tested it again and made a further version tag and the addon recognized it, I clicked install and it installed and asked me to restart. Now Blender displays the next version. Beautiful! Thank you kindly
