### ISSUE TITLE
Blender 2.93a - ValueError: Enable must be a boolean value

### ISSUE THREAD

**Issue by snotnose** [CGCookie/blender-addon-updater#70]
Hi, thanks for this addon. It's a great addition to my addon.
It seems like there is an Error when running the updater on Blender 2.93a from the Blender build.

> \blender-addon-updater-master\addon_updater.py", line 535, in set_check_interval
>     raise ValueError("Enable must be a boolean value")
> ValueError: Enable must be a boolean value

I'm assuming there was some API change for property assignment. Does anyone knows something about it?

**Comment by TheDuckCow** [comment]
Hi, I've gotten a couple similar issue requests from different addons I manage. I haven't sorted a solution yet, it may also be a sign that we need to more formally drop older 2.7x blender support (at the moment, this repo uses a workaround so the code can work in both 2.7x and 2.8+ versions of blender). In particular I imagine is the way of assigning annotations, but I could be wrong. 

If you beat me to it, do let me know what you uncover!

**Comment by snotnose** [comment]
Hi, Thanks for the quick response.
I thought it might be something with the property registeration. it mentions here something https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API but I'm not sure. 
I will also try to have a look, but I'm still not completly familiar with how the updater works.

**Comment by TheDuckCow** [comment]
Yes I saw that note as well. I think this indeed has something to do with it. I won't have time to get to testing if this is the case until later this weekend, but my first approach to try and validate is to temporary switch to use the annotation syntax in a local branch and see if that resolves the issues. If it does, I'll put some minimum threshold of effort to see if there's a way we can account for this _PropertyDeferred setup, but not holding my breath since it's self-described as "not considered part of the stable API".

**Comment by snotnose** [comment]
Hi, it was eventually just the property definition that was still written the old way in my addon.
instead of `auto_check_update = bpy.props.BoolProperty` I had to change to `auto_check_update: bpy.props.BoolProperty`
Somehow it was still working ok until Blender 2.92 but from 2.93 it has to be changed to  :

**Comment by TheDuckCow** [comment]
Hello all! Code has been merged so that blender 2.93 (and with my own testing, 3.0 as well) should now function. Would love for any sanity check of the current master code checked in to verify everything works as expected before I officially mark the release. There was another concurrent PR which made many changes now merged in. https://github.com/CGCookie/blender-addon-updater/pull/73

**Comment by ManPython** [comment]
Just change for 2.93 `=` for `:`
Or create version where this class can be imported by condition depend blender version.

```
@addon_updater_ops.make_annotations
class DemoPreferences(bpy.types.AddonPreferences):
	"""Demo bare-bones preferences"""
	bl_idname = __package__

	# addon updater preferences

	auto_check_update : bpy.props.BoolProperty(
		name="Auto-check for Update",
		description="If enabled, auto-check for updates using an interval",
		default=False,
		)
	updater_intrval_months : bpy.props.IntProperty(
		name='Months',
		description="Number of months between checking for updates",
		default=0,
		min=0
		)
	updater_intrval_days : bpy.props.IntProperty(
		name='Days',
		description="Number of days between checking for updates",
		default=7,
		min=0,
		max=31
		)
	updater_intrval_hours : bpy.props.IntProperty(
		name='Hours',
		description="Number of hours between checking for updates",
		default=0,
		min=0,
		max=23
		)
	updater_intrval_minutes : bpy.props.IntProperty(
		name='Minutes',
		description="Number of minutes between checking for updates",
		default=0,
		min=0,
		max=59
		)
```

**Comment by TheDuckCow** [comment]
I'm going to close this issue now since I've been using the change here in multiple of my own repo's now without issue. Appreciate the suggestion @ManPython, although it seems the merged fix works without having to maintain duplicate code which is always nice!
