### ISSUE TITLE
No module named 'blender-addon-updater-1'

### ISSUE THREAD

**Issue by ManPython** [CGCookie/blender-addon-updater#76]
This what I have when trying turn on the add-on after install.
`
blender\2.93\scripts\modules\addon_utils.py", line 351, in enable     mod = __import__(module_name) ModuleNotFoundError: No module named 'blender-addon-updater-1'
`

**Blender Version**
Broken: version: 2.93.0, branch: master, commit date: 2021-06-02 11:21, hash: `rB84da05a8b806`

**Comment by TheDuckCow** [comment]
Based on the name, I have a feeling there is a clash of the folder name, since it says it is looking for "blender-addon-updater-1" while the root repo is named "blender-addon-updater". Note that the module is specifically related to the name of the folder within the blender scripts/addon directory, rather than anything else hardcoded, and we reference this directory using the `__module__` dunder.

Can you try to manually delete all of the addon updater folders you might have in your addons folder, restart blender, and then try installing and running again?

**Comment by ManPython** [comment]
I changed `blender-addon-updater-1.0.8` to `blender-addon-updater`
My fault was coz I searched the `blender-addon-updater-1` in files, not recognized that .0.8 is cuted here.
Can be closed. Not sure is bug around addon or blender (limitation around dots?). Most of addons not using dots in m dir.. 

The name should be as `blender-addon-updater-1_0_8`

**Comment by TheDuckCow** [comment]
Sorry for the very long delay, but glad you were able to resolve! Yes, there are some general blender limitations around the names of folders for use of importing as modules, that would be my guess. Let me know if you found it to be otherwise.
