### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by LuWards** [CGCookie/blender-addon-updater#81]
Hello, when I click on "update to version 1.1.1, blender says i need to reload it but, when I do, the version still the same ( version 1,1,1).

**Comment by TheDuckCow** [comment]
Thanks for flagging! It was a mistake in the most recent release, the source code still had v1.1.0 in the init file, and thus was constantly thinking it was out of date.

I deleted the release & tag to push out the proper v1.1.1 (in production scenarios you might prefer another patch update instead of delete and re-generate release, in this case I chose this route since truly nothing else changed from that time).
